# Generated by Django 5.2.10 on 2026-01-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='category',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
